### ISSUE TITLE
Get JSON data using Javascript

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/weather-theme#1]
Instead of relying on PHP (which is fine) I'd like to try and get the JSON data via JS (because why not) and store it locally.

**Comment by blobaugh** [comment]
Possible lib to store data.
http://www.jstorage.info/

This will store using html5 local storage when possible. On browsers not supporting html5 it falls back to in memory. For even older browsers (Yes IE 6 is supported!) it simply does nothing. Your app will not error.
